high_school/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = i18n_patterns(
    path('', include('main.urls')),
    path('admin/', admin.site.urls),

    path('ckeditor/', include('ckeditor_uploader.urls')),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.welcome_view, name='welcome'),
    path('news/', views.news_view, name='news'),
    path('new/<int:pk>/', views.new_view, name='new'),
    path('page/<str:name>/', views.page_view, name='page'),
    path('direktors/', views.direktors_view, name='direktors'),
    path('teachers/', views.teachers_view, name='teachers'),
    path('teacher/<int:id>/', views.teacher_view, name='teacher'),
    path('about/', views.about_view, name='about'),
    path('contact-us/', views.contact_us_view, name='contact_us'),
]

main/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.


class New(models.Model):
    title = models.CharField(max_length=300, verbose_name='Title')  # translation
    image = models.ImageField(upload_to='./news/', default='/news/news.png')
    content = RichTextUploadingField(verbose_name='Content')  # translation

    create_at = models.DateTimeField(auto_now_add=True)
    upload_at = models.DateTimeField(auto_now=True)

    sees = models.IntegerField(verbose_name='See')
    likes = models.IntegerField(verbose_name='Like')

    def __str__(self):
        return self.title

    def sees_add(self):
        self.sees = self.sees + 1
        return self.save()

    def likes_add(self):
        self.likes = self.likes + 1
        return self.save()


class Director(models.Model):
    name = models.CharField(max_length=200, verbose_name='F.I.O')
    image = models.ImageField(null=True, blank=True, upload_to='./director/', default='/director/default.png')

    email = models.EmailField(verbose_name='Email', null=True)
    phone_number = models.CharField(max_length=50)

    content = RichTextUploadingField(null=True, blank=True, verbose_name='Malumot')  # translation
    position = models.CharField(max_length=250, verbose_name='Lavozimi')  # translation

    def __str__(self):
        return self.name


class Teacher(models.Model):
    name = models.CharField(max_length=200, verbose_name='F.I.O')
    image = models.ImageField(null=True, blank=True, upload_to='./director/', default='/director/default.png')

    email = models.EmailField(verbose_name='Email', null=True, blank=True)
    phone_number = models.CharField(max_length=50, null=True, blank=True)

    content = RichTextUploadingField(null=True, blank=True, verbose_name='Malumot')  # translation
    position = models.CharField(max_length=250, verbose_name='Lavozimi', blank=True, null=True)  # translation


class Page(models.Model):
    title = models.CharField(max_length=300, verbose_name='Title')  # translation
    image = models.ImageField(null=True, blank=True, upload_to='./pages/')
    content = RichTextUploadingField(verbose_name='Malumot')
    page_name = models.CharField(max_length=300, verbose_name='Page Name')

    def __str__(self):
        return self.title


class UserMessages(models.Model):
    first_name = models.CharField(max_length=100, verbose_name='Ismi')
    last_name = models.CharField(max_length=100, verbose_name='Familyasi')
    email = models.EmailField(max_length=100, verbose_name='Email')
    subject = models.CharField(max_length=250, verbose_name='Subject')
    message = models.TextField(verbose_name='Message')

    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subject

main/forms.py
from django.forms import ModelForm
from main.models import UserMessages


class UserMessagesForm(ModelForm):
    class Meta:
        model = UserMessages
        fields = ['first_name', 'last_name', 'email', 'subject', 'message']

main/views.py
from django.shortcuts import render, redirect
from .models import New, Director, Page, Teacher, UserMessages
from .forms import UserMessagesForm
from django.contrib import messages


def welcome_view(request):
    news = New.objects.all()[:3]
    directors = Director.objects.all()
    teachers = Teacher.objects.all()[:4]
    content = {
        'news': news,
        'directors': directors,
        'teachers': teachers,
    }
    return render(request, 'main/welcome.html', content)


def news_view(request):  # tamom  # pagination qilish kerak
    news = New.objects.all()
    if request.method == 'GET':
        search = request.GET.get('search')
        news_orders = New.objects.filter(title__icontains=search)[:12]
    else:
        news_orders = New.objects.all()[:12]
    content = {
        'news': news,
        'news_orders': news_orders,
    }
    return render(request, 'main/news.html', content)


def new_view(request, pk):  # tamom
    all_news = New.objects.all()[:6]
    new = New.objects.get(pk=pk)
    new.sees_add()
    new.likes_add()
    content = {
        'new': new,
        'news': all_news
    }
    return render(request, 'main/new.html', content)


def page_view(request, name):
    page = Page.objects.get(page_name=name)
    content = {
        'page': page,
    }
    return render(request, 'main/page.html', content)


def direktors_view(request):
    director = Director.objects.get(position_uz='Ijrochi Direktor')
    zamdirectors = Director.objects.all()

    content = {
        'director': director,
        'zamdirectors': zamdirectors[1:]
    }
    return render(request, 'main/direktor_zam.html', content)


def teachers_view(request):
    teachers = Teacher.objects.all()
    content = {
        'teachers': teachers,
    }
    return render(request, 'main/teachers.html', content)


def about_view(request):

    return render(request, 'main/about.html')


def contact_us_view(request):
    if request.method == "POST":
        form = UserMessagesForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f'{form.first_name} {form.last_name} your message sending :)')
            return redirect('/')
        else:
            return render(request, 'main/contact_us.html', {'form': form})
    return render(request, 'main/contact_us.html')


def teacher_view(request, id):
    pass

templates/main/contact_us.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}

    <!-- Start Header -->
    <div class="fables-header fables-after-overlay">
        <div class="container">
            <h2 class="fables-page-title fables-second-border-color">{% trans "Biz bilan bog'lanish" %}</h2>
        </div>
    </div>
    <!-- /End Header -->

    <!-- Start Breadcrumbs -->
    <div class="fables-light-gary-background">
        <div class="container">
            <nav aria-label="breadcrumb">
                <ol class="fables-breadcrumb breadcrumb px-0 py-3">
                    <li class="breadcrumb-item">
                        <a href="{% url 'main:welcome' %}" class="fables-second-text-color">
                            {% trans "Asosiy" %}
                        </a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">
                        {% trans "Biz bilan bog'lanish" %}
                    </li>
                </ol>
            </nav>
        </div>
    </div>
    <!-- /End Breadcrumbs -->


    <!-- Start page content -->
    <div class="container">
        <div class="row my-4 my-md-5 overflow-hidden">
            <div class="col-12 col-sm-6 col-md-4 text-center mb-4 mb-md-0 wow zoomIn" data-wow-duration="1.5s"
                 data-wow-delay=".4s">
                <span class="fables-iconmap-icon fa-2x fables-second-background-color text-white rounded-circle d-inline-block p-4"></span>
                <h2 class="font-16 semi-font fables-second-text-color my-3">
                    {% trans "Manzil" %}
                </h2>
                <p class="font-14 fables-forth-text-color">
                    {% trans "Toshkent, Yashnobod tumani, Sultonali Mashhadiy koʻchasi, 217/2" %}
                </p>

            </div>
            <div class="col-12 col-sm-6 col-md-4 text-center mb-4 mb-md-0 wow zoomIn" data-wow-duration="1.5s"
                 data-wow-delay=".8s">
                <span class="fables-iconphone fa-2x  fables-second-background-color text-white rounded-circle d-inline-block p-4"></span>
                <h2 class="font-16 semi-font fables-second-text-color my-3">
                    {% trans "Mail & Telefon Nomer" %}
                </h2>
                <p class="font-14 fables-forth-text-color">
                    <a href="mainto:stomalitsey@gmail.com" class="fables-second-text-color">
                        astomalitsey@gmail.com
                    </a>
                </p>
                <p class="font-14 fables-forth-text-color">
                    <a href="tel:+998 71 235 32 45" class="fables-second-text-color">
                        +998 71 235 32 45
                    </a>
                </p>
            </div>
            <div class="col-12 col-sm-6 col-md-4 text-center mb-4 mb-md-0 wow zoomIn" data-wow-duration="1.5s"
                 data-wow-delay="1.2s">
                <span class="fables-iconshare-icon fa-2x fables-second-background-color text-white rounded-circle d-inline-block p-4"></span>
                <h2 class="font-16 semi-font fables-second-text-color my-3">
                    {% trans "Ijtimoiy tarmoqlarda" %}
                </h2>
                <ul class="nav fables-contact-social-links">
                    <li><a href="#" target="_blank"><i class="fab fa-facebook-f fables-forth-text-color fa-fw"></i></a>
                    </li>
                    <li><a href="#" target="_blank"><i class="fab fa-instagram fables-forth-text-color  fa-fw"></i></a>
                    </li>
                    <li><a href="#" target="_blank"><i class="fab fa-twitter fables-forth-text-color    fa-fw"></i></a>
                    </li>
                    <li><a href="#" target="_blank"><i class="fab fa-linkedin fables-forth-text-color   fa-fw"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="fables-contact-caption fables-after-overlay px-2 px-sm-5 text-left text-sm-center py-5 bg-rules">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-8 offset-lg-2">
                    <h3 class="font-25 font-weight-bold white-color position-relative z-index">
                        We are the best business consulting company ever!!
                    </h3>
                    <p class="font-weight-light fables-third-text-color my-3 position-relative z-index">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac lorem pretium laoreet
                        enim at, malesuada Class aptent taciti sociosqu.
                    </p>
                    <a href="{% url 'main:about' %}"
                       class="btn fables-second-background-color fables-rounded-btn white-color fables-btn-rounded font-19 px-5 mt-2 position-relative z-index">
                        {% trans "Ko'proq bilish" %}
                    </a>
                </div>

            </div>

        </div>
    </div>
    <div class="container">
        <div class="row my-4 my-md-5">
            <div class="col-12 col-md-10 offset-md-1 col-lg-8 offset-lg-2">
                <h3 class="font-35 font-weight-bold fables-second-text-color text-center mb-3">
                    {% trans "Biz bilan bog'lanish" %}
                </h3>
                <p class="fables-forth-text-color text-center">
                    {% trans "Sizni qiziqtirgan savolingiz bo'yicha pastdagi formani to'ldirib yuborishingiz mumkin. Email manzilingizga javob yuboriladi." %}
                </p>
            </div>
        </div>
        <div class="row overflow-hidden">
            <div class="col-12 wow slideInLeft" data-wow-duration="1.5s">
                <form class="fables-contact-form" method="post" action="{% url 'main:contact_us' %}">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <input type="text" name="first_name" class="form-control p-3 rounded-0"
                                   placeholder="{% trans 'Ismingiz' %}" required value="{{ form.first_name.data }}">
                        </div>
                        <div class="form-group col-md-6">
                            <input type="text" name="last_name" class="form-control p-3 rounded-0"
                                   placeholder="{% trans 'Familyangiz' %}" required value="{{ form.last_name.data }}">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <input type="email" name="email" class="form-control p-3 rounded-0" placeholder="Email" required
                            value="{{ form.email.data }}">
                        </div>
                        <div class="form-group col-md-6">
                            <input type="text" name="subject" class="form-control p-3 rounded-0"
                                   placeholder="{% trans 'Mavzu' %}" required value="{{ form.subject.data }}">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <textarea class="form-control p-3 rounded-0" name="message"
                                      placeholder="{% trans 'Habar' %}" rows="4">{{ form.message.data }}</textarea>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12 text-center">
                            <button type="submit"
                                    class="btn fables-second-background-color fables-btn-rounded white-color px-7 font-20 py-2">
                                {% trans "Yuborish" %}
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- /End page content -->

{% endblock %}

templates/main/new.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block content %}

    <!-- Start Breadcrumbs -->
    <div class="fables-light-gary-background">
        <div class="container">
            <nav aria-label="breadcrumb">
                <ol class="fables-breadcrumb breadcrumb px-0 py-3">
                    <li class="breadcrumb-item">
                        <a href="{% url 'main:welcome' %}" class="fables-second-text-color">
                            {% trans "Asosiy" %}
                        </a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="{% url 'main:news' %}" class="fables-second-text-color">
                            {% trans "Yangiliklar" %}
                        </a>
                    </li>
                    <li class="breadcrumb-item">
                        {% trans "Yangilik" %}
                    </li>
                </ol>
            </nav>
        </div>
    </div>

    <!-- /End Breadcrumbs -->

    <!-- Start page content -->
    <div class="container">
        <div class="my-4 my-lg-4">
            <div class="owl-carousel owl-theme default-carousel nav-0 single-blog">
                <div>
                    <a href="{{ new.image.url }}" target="_blank">
                        <img src="{{ new.image.url }}" alt="" class="w-100">
                    </a>
                </div>
                <div>
                    <a href="{{ new.image.url }}" target="_blank">
                        <img src="{{ new.image.url }}" alt="" class="w-100">
                    </a>
                </div>
                <div>
                    <a href="{{ new.image.url }}" target="_blank">
                        <img src="{{ new.image.url }}" alt="" class="w-100">
                    </a>
                </div>
            </div>
            <h2 class="font-23 semi-font">
                <a href="{% url 'main:new' new.id %}" class="fables-main-text-color fables-second-hover-color">
                    {{ new.title }}
                </a>
            </h2>
            <p class="fables-forth-text-color font-14 my-4">
                {{ new.content |safe }}
            </p>
            <div class="fables-forth-text-color fables-blog-date">
                <div class="row">
                    <div class="col-12 col-md-9 col-lg-10 pt-2">
                        <span class="fables-icondata fables-second-text-color mr-1"></span>
                        <span class="mr-3 font-15">{{ new.create_at|date:"d:m:Y" }}</span>|
                        <span class="mr-3 font-15">{{ new.create_at|time:"H:i" }}</span>

                        <a href="#" class="fables-forth-text-color fables-second-hover-color position-relative z-index">
                            <span class="fables-iconeye fables-second-text-color mr-1"></span>
                            {{ new.sees }}
                        </a>
                        |
                        <a href="#" class="fables-forth-text-color fables-second-hover-color position-relative z-index">
                            <span class="fables-iconheart fables-second-text-color mr-1"></span>
                            {{ new.likes }}
                        </a>
                    </div>
                    <div class="col-12 col-md-3 col-lg-2 text-right mt-3 mt-md-0 text-center text-md-right">
                        <button class="btn btn-link fables-fifth-border-color fables-forth-hover-backround-color fables-forth-text-color "
                                onclick="window.print();"><span
                                class="fables-iconprint"></span> {% trans "Chop Etish" %}
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <div class="row overflow-hidden">
            <div class="col-12 col-md-7 col-lg-8 wow fadeInRight" data-wow-delay=".8s">

            </div>
        </div>

        <div class="my-4 my-lg-5">
            <h2 class="fables-main-text-color text-center underline my-4 font-25 semi-font mb-5">Boshqa yangiliklar</h2>
            <div class="owl-carousel owl-theme fables-main-dots carousel-items-4 mb-0 mb-lg-5">
                {% for all_new in news %}
                    <div>
                        <div class="image-container zoomIn-effect">
                            <a href="{% url 'main:new' all_new.id %}">
                                <img src="{{ all_new.image.url }}" alt="" class="w-100">
                            </a>
                        </div>
                        <div class="fables-forth-text-color font-14  my-2">
                            <span class="fables-icondata fables-second-text-color mr-1"></span>
                            <span class="mr-3"> {{ all_new.create_at }} </span>
                            <span class="fables-iconeye fables-second-text-color mr-1"></span>
                            <a href=""
                               class="fables-forth-text-color fables-second-hover-color position-relative z-index">{{ all_new.sees }}</a>
                        </div>
                        <h2 class="font-18 semi-font">
                            <a href="{% url 'main:new' all_new.id %}"
                               class="fables-main-text-color fables-second-hover-color">
                                {{ all_new.title|slice:75 }}
                            </a>
                        </h2>
                        <a href="" class="btn fables-second-text-color fables-main-hover-color font-14 p-0 my-3">
                            {% trans "O'qish" %}
                            <i class="fas fa-chevron-right"></i></a>
                    </div>
                {% endfor %}
            </div>
        </div>

    </div>
    <!-- /End page content -->


{% endblock %}

{{ new.content | safe }}

templates/main/news.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block content %}

    <!-- Start Header -->
    <div class="fables-header fables-after-overlay">
        <div class="container">
            <h2 class="fables-page-title fables-second-border-color">{% trans "Akademik Litsey Yangiliklari" %}</h2>
        </div>
    </div>
    <!-- /End Header -->

    <!-- Start Breadcrumbs -->
    <div class="fables-light-gary-background">
        <div class="container">
            <nav aria-label="breadcrumb">
                <ol class="fables-breadcrumb breadcrumb px-0 py-3">
                    <li class="breadcrumb-item"><a href="{% url 'main:welcome' %}"
                                                   class="fables-second-text-color">{% trans "Asosiy" %}</a></li>
                    <li class="breadcrumb-item active"
                        aria-current="page">{% trans "Akademik Litsey Yangiliklari" %}</li>
                </ol>
            </nav>
        </div>
    </div>
    <!-- /End Breadcrumbs -->

    <!-- Start page content -->
    <div class="container">
        <div class="row my-4 my-md-5">
        <!-- Start Last news -->
            <div class="col-12 col-md-4 col-lg-3">
                <div class="fables-store-search mb-4">
                    <form method="get" action="{% url 'main:news' %}">

                        <div class="input-icon">
                            <span class="fables-iconsearch-icon fables-input-icon"></span>
                            <input type="text" name="search"
                                   class="form-control rounded-0 form-control rounded-0 font-14 fables-store-input pl-5 py-2"
                                   placeholder="Search Product">
                        </div>
                    </form>
                </div>
                <h2 class="font-16 semi-font fables-forth-text-color fables-light-gary-background  p-3 my-4">
                    {% trans "So'ngi yangiliklar" %}
                </h2>
                {% for news_order in news_orders %}
                    <div class="row mb-3">
                        <div class="col-4 pr-0">
                            <a href="{% url 'main:new' news_order.id %}">
                                <img src="{{ news_order.image.url }}" alt="" class="w-100">
                            </a>
                        </div>
                        <div class="col-8">
                            <a href="{% url 'main:new' news_order.id %}"
                               class="fables-main-text-color font-14 semi-font fables-second-hover-color store-card-text">
                                {{ news_order.title |slice:34 }}
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>

            <div class="col-12 col-md-8 col-lg-9">
                <div class="row mb-4">
                    <div class="col-4 col-md-6 col-lg-2 offset-lg-6 text-center pl-0 d-none d-lg-block">
                        <span class="fables-iconlist fa-fw fables-view-btn fables-list-btn fables-third-border-color fables-third-text-color"></span>
                        <span class="fables-icongrid active fa-fw fables-view-btn fables-grid-btn fables-third-border-color fables-third-text-color"></span>
                    </div>
                </div>

            <!-- start news -->
                <div class="row">
                    {% for new in news %}
                        <div class="col-12 col-sm-6 col-lg-4 fables-product-block">
                            <div class="card rounded-0 mb-4">
                                <div class="row">
                                    <div class="fables-product-img col-12">
                                        <img class="card-img-top rounded-0"
                                             src="{{ new.image.url }}"
                                             alt="dress fashion" height="180">
                                        <div class="fables-img-overlay">
                                            <ul class="nav fables-product-btns">
                                                <li>
                                                    <a href="{% url 'main:new' new.pk %}"
                                                       class="fables-product-btn">
                                                        <span class="fables-iconeye"></span>
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="" class="fables-product-btn">
                                                        <span class="fables-iconcompare">
                                                        </span>
                                                    </a>
                                                </li>
                                                <li>
                                                    <button class="fables-product-btn">
                                                        <span class="fables-iconheart">
                                                        </span>
                                                    </button>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="card-body col-12">
                                        <p class="store-card-text fables-fifth-text-color font-15 mx-xl-3">
                                            <a href="{% url 'main:new' new.id %}"
                                               class="fables-main-text-color fables-store-product-title fables-second-hover-color">
                                                {{ new.title |slice:68 }}
                                            </a>
                                        </p>
                                        <hr>
                                        <span class="fables-icondata fables-second-text-color mr-1"></span>
                                        <span class="mr-3 font-15">{{ new.create_at|date:"d:m:Y"}}</span>|<span class="mr-3 font-15">{{ new.create_at|time:"H:i" }}</span>
                                        <br>

                                        <p class="fables-product-info">
                                            <a href="{% url 'main:new' new.id %}"
                                               class="btn fables-second-border-color fables-second-text-color fables-btn-rouned fables-hover-btn-color font-14 p-2 px-2 px-xl-4">
                                                <span class="fables-btn-value"> {% trans "To'liq ko'rish" %}</span></a>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            <!-- End news -->

            <!-- Start pagination -->
                <nav aria-label="Page navigation">
                    <ul class="pagination justify-content-center">
                        <li class="page-item"><a
                                class="page-link rounded-circle fables-forth-text-color fables-page-link fables-second-hover-background-color"
                                href="#">1</a></li>
                        <li class="page-item"><a
                                class="page-link rounded-circle fables-forth-text-color fables-page-link fables-second-hover-background-color"
                                href="#">2</a></li>
                        <li class="page-item"><a
                                class="page-link rounded-circle fables-forth-text-color fables-page-link fables-page-link fables-second-hover-background-color"
                                href="#">3</a></li>
                        <li><span class="fables-pagi-dots fables-forth-text-color"> .... </span></li>
                        <li class="page-item"><a
                                class="page-link rounded-circle fables-forth-text-color fables-page-link fables-second-hover-background-color"
                                href="#">20</a></li>
                    </ul>
                </nav>
            <!-- End pagination -->
            </div>
        </div>
    </div>
    <!-- /End page content -->

{% endblock %}